### ISSUE TITLE
Gather home-landing and system-detail code + content.

### ISSUE THREAD

**Issue by nsoteriou** [urbanspectra-nyc/nycsys#1]
This requires local edits, adds, commits (with log messages).

We are OFTEN using $ git status
to verify our expectations.

Then, after being locally up-to-date with git,
update REMOTE github rep with:

$ git push

**Comment by nsoteriou** [comment]
This requires local edits, adds, commits (with log messages) -- the first solo local git workflow:
$ git status
$ git init/clone
$ git status
( $ git push later)
[edits]
$ git status
$ git add .
$ git commit - m "added some code + contact"
$ git status
$ git log 

I want to work on branching soon

=> Ideal commit messages include:
-  what I did (AT MINIMUM)
- why I did it (issue #?)
- tests to foster approval

Branching will soon be added, so that we can speak to dev, qa and prod branches in a single repo.

**Comment by jdonson** [comment]
This is great!

I look forward to redesigns...  <3
