### ISSUE TITLE
Replace name from sofiasys to nycsys

### ISSUE THREAD

**Issue by nsoteriou** [urbanspectra-nyc/nycsys#3]
-- Must find all text "sofiasys", change to nycsys

**Comment by nsoteriou** [comment]
How do i make a git hub page so you can approve this change on that page?

**Comment by nsoteriou** [comment]
reopened - need to get remote approval thru github pages....

See issue #5.

**Comment by nsoteriou** [comment]
nsoteriou.github.io/system-detail.html

**Comment by jdonson** [comment]
this looks great for both pages, thanks!
