### ISSUE TITLE
Use github pages for approvals

### ISSUE THREAD

**Issue by jdonson** [urbanspectra-nyc/nycsys#5]
This is a basic feature, as we need to do approvals thru github.....

We have two static pages targeted for this project:
1.  home-landing page
2.  systems-detail page

Learning to share a page thru github is KEY for approvals!

**Comment by jdonson** [comment]
https://pages.github.com/

Please create a page at github for approval with regard to #3

**Comment by jdonson** [comment]
You seemed to follow the instructions just right....
I went to the following url and saw "Hello world".
http://nsoteriou.github.io/
Can you copy the home-landing.html page to that folder where you have text edits to get approved?
(See #3 for those details.)

If so, then we can close this issue!!  (y)

**Comment by nsoteriou** [comment]
nsoteriou.github.io/system-detail.html

**Comment by jdonson** [comment]
I was able to view that page, however...
Corrections:
1.  this is not the correct page, and the url is also slightly off
=> please come from urbanspectra.com/sofiasys/
2.  styles/iphone.css is not where the css file exists.
=> please make sure that css file is properly referenced
3.  Please consider putting three directories beneath that
nsoteriou.github.io  personal approval pages folder:
1.  nycsys
2.  color
3.  events

Then I could approve the nycsys project pages under:
nsoteriou.github.io/nycsys/{filename}

**Comment by nsoteriou** [comment]
-- first correction is clear, and I will come fro, that correct page
-- I fixed the reference to css file - code pending.
-- So you suggest three project subfolders underneath my approval folder?
?? we are only working on the first two projects first, ok?

**Comment by jdonson** [comment]
Thanks, yes, two projects (nycsys + webcolor) is PLENTY to start with....
Please notify me when you have those urls up for approval:
http://nsoteriou.github.io/nycsys/ (index.html)
http://nsoteriou.github.io/nycsys/system-detail.html

**Comment by jdonson** [comment]
I just saw two pages that look pretty good!

That means that you are now using github pages for approvals!

be sure to refer back to this issue if that requires some better review.
